### ISSUE TITLE
Buttons 

### ISSUE THREAD

**Issue by mercykolapo** [Custos-Diretriz/custos-starknet#1]
As shown in the design prototype, the buttons are not animated at all. From the component below, the button is supposed to change on hover

![image](https://github.com/user-attachments/assets/5fa4c355-b454-49a5-a8b6-ea06266d14ec)

**Comment by mercykolapo** [comment]
![image](https://github.com/user-attachments/assets/d6daa4f5-d301-42b3-8a2e-028b2841db97)
The button on the live website isn't same as the design. The strokes have issues.

**Comment by mercykolapo** [comment]
![image](https://github.com/user-attachments/assets/8a0c831a-de58-4756-a8b7-fc7c953d5307)
This is small as compared to the design
![image](https://github.com/user-attachments/assets/b149a2ff-e46d-4f26-b30a-a3123f8ef09f)
What we have in the design

**Comment by custosDiretriz** [comment]
@jerydam i assigned this issue to you
