### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Khauthymo** [Custos-Diretriz/custos-starknet#2]
- [x] Implement cairo test for crime recorder contract
- [x] Implement tests for agreement contracts

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a full stack and web3 developer with experience in writing tests for smart contracts using cairo. I have written tests for other projects on onlydust. Here is my profile: https://app.onlydust.com/u/No-bodyq

### How I plan on tackling this issue
I have write write tests for all the function present in the crime recorder and agreement contracts taking into account all edge cases and test for access controls

**Comment by casweeney** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.

### How I plan on tackling this issue
With my versatile skill in Cairo testing having tested complex Cairo smart contracts, I will approach this by testing every function that makes up the `Agreement` and `CrimeRecord` contract. I will check for all assertions in the contract functions and also test for access controls.

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello! My name is Lukman, a passionate Smart Contract Developer with 2 years of experience writing smart contracts. I have  hands-on experience spans various blockchain platforms, including Ethereum and Starknet.

### How I plan on tackling this issue
To implement tests for the Crime Recorder contract, I will first identify the core functionalities and edge cases that need validation, creating a structured testing plan. For the Agreement contracts, I will analyze the contract specifications to define test scenarios, leveraging Cairo's testing framework to ensure comprehensive coverage and correctness of all interactions and expected outcomes.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### How I plan on tackling this issue
I will develop a comprehensive test suite for both the Agreement and Crime Recorder contracts following TDD principles. For the Agreement contract, tests will cover the complete agreement lifecycle, including creation, validation flows, and query functions. The Crime Recorder tests will focus on record management, access control, and data retrieval functionality. I'll create robust test infrastructure with helpers and mock data generators, aiming for >90% coverage across both contracts. Tests will include both success and failure paths, with clear documentation of test scenarios. The implementation will coordinate with the Cairo 2.7.0 upgrade to ensure compatibility. Expected completion time is 3 days, covering setup, implementation, and verification of both contract test suites.

**Comment by Pvsaint** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm Victor Peter, a front-end and smart contract developer.

### How I plan on tackling this issue
Create test cases that cover different scenarios, such as:
Creating a new crime record
Updating an existing crime record
Deleting a crime record
Retrieving a list of crime records

**Comment by GideonBature** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a Software Engineer and Open-source contributor, with experience in Rust, JavaScript, TypeScript and of recent Cairo. I have participated the in the last two ODhack and have made considerable contribution to the Starknet Ecosystem. I have written various Cairo contracts including the unit tests and integration tests for those contracts. These tests covers testing for functions and events etc.

### How I plan on tackling this issue
I will first go through the two contracts and make a list of all the functions and events that are emitted by those functions.

Next, I will start implementing those tests one after the other, utilising `snfoundry` for the tests. Will be testing for both the functions in the two contracts and the events those functions in the contracts are emitting.

**Comment by Yunusabdul38** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a strong background in software development, with a focus on blockchain technologies and smart contract development. My experience spans across various domains including decentralized applications (dApps), smart contract testing, and blockchain infrastructure.

With proficiency in Cairo (language), I am adept at writing and testing contracts on different blockchain platforms. I have hands-on experience with the StarkNet ecosystem and the Cairo programming language, which allows me to efficiently develop and test complex smart contracts.

Additionally, my experience with automated testing frameworks, version control systems, and continuous integration (CI) pipelines equips me to approach contract testing in a robust and scalable manner. My background in full-stack development, specifically with React and TypeScript, further strengthens my ability to contribute effectively to the frontend of decentralized applications, ensuring seamless integration with smart contracts.

Leveraging this experience, I can thoroughly implement and optimize the Cairo tests for the crime recorder and agreement contracts, ensuring high reliability and security.

### How I plan on tackling this issue
To approach the problem, I would begin by reviewing the crime recorder and agreement contracts to understand their requirements and potential edge cases. For the crime recorder contract, I would focus on testing the data recording and verification processes, ensuring it handles edge cases securely. For the agreement contracts, I would ensure that all terms are enforced correctly under various scenarios.

I would implement unit and integration tests using the Cairo framework and set up continuous integration for automated test execution. This would help ensure contract reliability and detect issues early

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
with an experience in writing test for smart contracts using cairo and solidity i would be able to handle. Kindly assign me.

### How I plan on tackling this issue
Using cairo I would write test to check the state of the contract before and after the crime recorder and agreement contract has been called

**Comment by jsandinoDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm a full-stack developer with web3 experience, specializing in smart contracts and decentralized applications. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

### How I plan on tackling this issue
. Understand the Contracts
Ensure you fully understand the functionality of the Crime Recorder and Agreement contracts, including:

What events or data they manage.
What key functions need testing (e.g., adding crimes, creating agreements, etc.).
Expected results for each function (e.g., state changes, returned values).

2. Set Up Cairo Test Environment

3. Write Tests 
4. Run the Tests

**Comment by Goodness5** [comment]
@casweeney wait for the issue #3 to be submitted before proceeding with this

**Comment by casweeney** [comment]
> @casweeney wait for the issue #3 to be submitted before proceeding with this

Alright, thanks for the opportunity.

**Comment by Goodness5** [comment]
@casweeney you can pull and proceed with the tests the issues have been resolved
