### ISSUE TITLE
Make agreement contract upgradable

### ISSUE THREAD

**Issue by Goodness5** [Custos-Diretriz/custos-starknet#4]
Your task is to make the agreement contract upgradable. 

- Use the latest Cairo syntax for the implementation.
- Use Upgradable component from Openzeppelin contract
- Apply access control

**Comment by OkoliEvans** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I will also like to handle this issue @Goodness5 
I have been contributing to open source projects on starknet for a year now, and most of my contributions involve writing Cairo smart contracts. I believe my experience over the year has equipped me with the advanced skills and experience to handle advanced Cairo contracts.

**Comment by casweeney** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.

### How I plan on tackling this issue
I will first import the openzeppelin `UpgradeableComponent` in the `Agreement` contract, then I will implement the `InternalImpl` of `UpgradeableComponent` from which I will get access to the `_upgrade` function. I will create an external function called `upgrade` which only the contract owner can call. The `upgrade` function will be responsible for upgrading the `Agreement` contract, it will take in an argument of `class_hash` of type `ClassHash` which will be passed into the `_upgrade()` function from openzeppelin `UpgradeableComponent`

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### How I plan on tackling this issue
I will implement upgradability by integrating OpenZeppelin's upgradeable and ownable components into the Agreement contract. The solution involves modifying the storage structure to include component substorage, implementing proper access control through the Ownable pattern, and adding an upgrade mechanism with owner-only restrictions. I'll ensure storage safety by maintaining the existing layout and adding version tracking. The implementation will include comprehensive testing of the upgrade functionality, storage persistence, and access controls. Documentation will cover the upgrade process, storage layout changes, and upgrade instructions. Expected completion time is 2-3 days, covering implementation, testing, and documentation.

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
I''ll be using the Upgradable component from Oz to upgrade the contract and use access control component from Oz to implement role-based access control mechanisms for the contract.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.


### How I plan on tackling this issue
i will Use OpenZeppelin's Upgradable component.
Implement access control.
Test the contract thoroughly.

**Comment by GideonBature** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a Software Engineer and Open-source contributor, with experience in Rust, JavaScript, TypeScript and of recent Cairo. I have participated the in the last two ODhack and have made considerable contribution to the Starknet Ecosystem. I have written various contracts that implements the ownable and erc20 components of Openzeppelin. I believe I will be able to apply that experience and knowledge in implementing the Upgradable component from Openzeppelin.

### How I plan on tackling this issue
I am going to first of all import the Upgradable component from Openzeppelin, including the path, storage and event. Then I will go ahead and implement the Upgradable component to make the agreement contract upgradable including access control.

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm Joseph a blockchain developer with over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Begin by studying the codebase to ensure design consistency, then proceed to work on the task.

1. Study current codebase design
2. Leverage all provided resources within the issue to get a better grasp of the task at hand.
3. Implement the task.
4. Add tests to make sure the changes are working and no adverse effects
5. And lastly optimize
