### ISSUE TITLE
Refactor Contributing guidelines

### ISSUE THREAD

**Issue by faytey** [Custos-Diretriz/custos-starknet#8]
- [ ] Refactor Contributing Guidelines to include detailed reproducible methods, including installation of needed dependencies to successfully run the project and tests successfully.

**Comment by Bosun-Josh121** [comment]
Mind if I try this one?

**Comment by Benjtalkshow** [comment]
Can I tackle this one?

**Comment by Michaelkingsdev** [comment]
Would love to tackle this!

**Comment by 0xdevcollins** [comment]
I’d like to resolve this.

**Comment by Kingsuite** [comment]
I’d love to work on this task. ETA 24HRS

**Comment by Kaminar-i** [comment]
Is it okay if I tackle this?
please kindly assign

**Comment by faytey** [comment]
Thanks everyone for your interest in this issue, please apply through onlydust.

**Comment by martinvibes** [comment]
I’m interested in this one.
hello can i work on this issue :)

**Comment by Jemiiah** [comment]
Can I contribute to this one?

**Comment by petersdt** [comment]
I would implement the above covering the following aspect of the current guideline:

- Code of Conduct
- How to Contribute
- Development Environment Setup
- Project Setup
- Branching and Commit Guidelines
- Pull Requests
- Coding Standards
- Testing Guidelines
- Issue Reporting
- Resources
- License

with detailed examples where required especially for testing, Project setup and work flow examples

ETA 24hrs

previous contribution:

- [cairo book](https://github.com/cairo-book/cairo-book/pull/788)

**Comment by 0xBinayak** [comment]
I’d love to work on this task abd would  like to resolve this.I would reallyhave fun contributing tto this repo
